# flake8: noqa: PYI021
def add(left: int, right:int) -> int:
    """Return the sum of two integers."""


def hello(name: str) -> str:
    """Return a greeting generated by Rust."""


def sleep_detached(milliseconds):
    """Sleep without holding Python's GIL."""
