name: Run automatoes tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up peeble
        run: |
          export GOPATH=~/go
          ./scripts/install_pebble.sh
      - name: Install dependencies
        run: |
          pip install -r requirements/development.txt
      - name: Run python behave tests
        run: |
          export GOPATH=~/go
          ./scripts/pebble_service.sh start tests/conf/pebble-config.json
          behave tests/features
          ./scripts/pebble_service.sh stop tests/conf/pebble-config.json
