name: Run automatoes tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.13.1'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up peeble
        run: |
          export GOPATH=~/go
          ./scripts/install_pebble.sh
      - name: Install dependencies
        run: |
          pip install -r requirements/development.txt
      - name: Run python unit tests
        run: |
          PYTHONPATH=$PYTHONPATH:. python tests/runtests.py
      - name: Run python behave tests
        run: |
          export GOPATH=~/go
          ./scripts/pebble_service.sh start tests/conf/pebble-config.json
          behave tests/features
      - name: Lint
        run: |
          echo "::error file=automatoes/acme.py,line=87,col=17,endLine=87,endColumn=42,title=TEST::This is an annotation test"
          echo "::warning file=automatoes/acme.py,line=87,title=TEST::This is a warning test"
          echo "::error file=/home/runner/work/automatoes/automatoes/automatoes/acme.py,line=20,col=1,endLine=33,endColumn=43::[I001] Import block is un-sorted or un-formatted"
      - name: Build packages
        run: |
          ./scripts/build.sh
