use pyo3::prelude::*;
use std::time::Duration;

/// Return a greeting generated by Rust.
#[pyfunction]
fn hello(name: &str) -> String {
    format!("Hello, {name}! Rust is handling this function.")
}

/// Return the sum of two integers.
#[pyfunction]
fn add(left: i64, right: i64) -> i64 {
    left + right
}

/// Sleep without holding Python's GIL.
#[pyfunction]
fn sleep_detached(py: Python<'_>, milliseconds: u64) {
    py.detach(|| {
        std::thread::sleep(Duration::from_millis(milliseconds));
    });
}

#[pyfunction]
fn automatoes_hello() -> String {
    automatoes::hello().to_owned()
}

/// Python module implemented in Rust.
#[pymodule]
fn rust_backend(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_function(wrap_pyfunction!(hello, module)?)?;
    module.add_function(wrap_pyfunction!(add, module)?)?;
    module.add_function(wrap_pyfunction!(sleep_detached, module)?)?;
    module.add_function(wrap_pyfunction!(automatoes_hello, module)?)?;
    Ok(())
}
